/**
 * Compute index projections from a matrix generated by factors.
 * That is, given U, S, V', and a set of indicies i, j
 * set A = U*S*V', and return A(i(1),j(1)), A(i(2),j(2)), ... A(i(n),j(n))
 * without computing all of A
 *
 * @author David F. Gleich
 *
 * History
 * -------
 * :2009-11-08: Initial coding
 * :2009-11-23: Added uint32 and int32 choices
 */

#include <mex.h>
#include "mexhelp.h"

void mexFunction(
        int nargout, mxArray *pargout[],
        int nargin, const mxArray *pargin[])
{
    mwIndex i, j;
    double *Uk, *Sk, *Vk, *v, *fi, *fj;
    mwSize m, n, k, N;
    if (nargin  != 5 || nargout != 1) {
        mexErrMsgTxt ("Usage: v = indexprojfact(U,S,V,i,j)") ;
    }
    m = mxGetN(pargin[0]);
    k = mxGetNumberOfElements(pargin[1]);
    n = mxGetN(pargin[2]);
    N = mxGetNumberOfElements(pargin[3]);
    
    Uk = cs_mex_get_double_mat(k, m, pargin[0]);
    Sk = cs_mex_get_double(k, pargin[1]);
    Vk = cs_mex_get_double_mat(k, n, pargin[2]);
    
    pargout[0] = mxCreateDoubleMatrix(N,1,mxREAL);
    v = mxGetPr(pargout[0]);
    
    if (mxGetClassID(pargin[3]) == mxINT32_CLASS) {
        int *ii=cs_mex_get_int_data(N,pargin[3]);
        int *ij=cs_mex_get_int_data(N,pargin[4]);
        for (i=0; i<N; i++) {
            mwIndex ri=(mwIndex)(ii[i]), cj=(mwIndex)(ij[i]);
            v[i] = 0;
            for (j=0; j<k; j++) {
                v[i] += Uk[ri*k + j]*Sk[j]*Vk[cj*k + j];
            }
        }
    } else if (mxGetClassID(pargin[3]) == mxUINT32_CLASS) {
        unsigned int *ii=cs_mex_get_uint_data(N,pargin[3]);
        unsigned int *ij=cs_mex_get_uint_data(N,pargin[4]);
        for (i=0; i<N; i++) {
            mwIndex ri=(mwIndex)(ii[i]), cj=(mwIndex)(ij[i]);
            v[i] = 0;
            for (j=0; j<k; j++) {
                v[i] += Uk[ri*k + j]*Sk[j]*Vk[cj*k + j];
            }
        }
    } else {
        double *fi = cs_mex_get_double(N, pargin[3]);
        double *fj = cs_mex_get_double(N, pargin[4]);
        for (i=0; i<N; i++) {
            mwIndex ri=(mwIndex)(fi[i]-1), cj=(mwIndex)(fj[i]-1);
            v[i] = 0;
            for (j=0; j<k; j++) {
                v[i] += Uk[ri*k + j]*Sk[j]*Vk[cj*k + j];
            }
        }
    }
}

